spring:
    datasource:
        name: every
        url: jdbc:mysql://localhost:3306/every?useUnicode=true&characterEncoding=utf-8
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

mybatis:

mybatis-plus:
#  mapper-locations: classpath:/mapper/*DAO.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.lyways.business.user.entity
  type-handlers-package: com.lyways.tool.jdbc.adapter.mybatis
#  typeEnumsPackage: com.baomidou.springboot.entity.enums
  configuration:
    mapUnderscoreToCamelCase: true
  global-config:
    meta-object-handler: com.lyways.tool.jdbc.adapter.mybatis.MybatisMetaObjectHandler

logging:
    level:
        root:DEBUG